[package]
name = "ctflag_derive"
version = "0.1.0"
authors = ["Adam Lesinski <adamlesinski@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["extra-traits"] }
unicode-segmentation = "1.3"